### PR TITLE
Add encryption and decryption to config file

### PR DESCRIPTION
**Pull request by KevinLu**
TODO:

- Decrypt config file when using `watcard -f`
- Add password required to do commands if a `.key` file exists

### CODE REVIEW

**Comment by xingweitian** [comment]
I am back. I will update this PR soon.

**Comment by xingweitian** [comment]
@KevinLu I changed the logic, it seems that unsafe to store the key file locally, so why not we don't store it, we can only depend on the user's password, which means that user should remember him/her password, otherwise he/she will not decrypt the config file successfully.
What do you think?

**Comment by KevinLu** [comment]
Yes, storing the key file is not safe as it can be stolen. Now the problem is how can we authenticate the user without storing the password?

**Comment by xingweitian** [comment]
> Yes, storing the key file is not safe as it can be stolen. Now the problem is how can we authenticate the user without storing the password?

Here is my think.
Users use password to encrypt the config file, and when they want to decrypt, they should use the same password.
It means that we provide a transparent encryption mechanism and user should remember the password, only the same password can decrypt the config file correctly.
Does it make sense?

**Pull request merged**
